services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=timewars'
      - 'POSTGRES_PASSWORD=timewars-secret'
      - 'POSTGRES_USER=ravn'
    ports:
      - '5432:5432'
    volumes:
      - '~/volumes/ravn-timewars/postgres:/var/lib/postgresql/data'