logging:
  level:
    ROOT: INFO
    org.hibernate.SQL: INFO
    com.ravn.timewars: INFO

spring:
  application:
    name: TimeWars Backend
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: false
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
          batch_size: 25
        query:
          fail_on_pagination_over_collection_fetch: true
          in_clause_parameter_padding: true
        generate_statistics: false
        order_updates: true
        connection:
          provider_disables_autocommit: true
        order_inserts: true
        default_schema: timewars_db
        format_sql: true
    hibernate:
      ddl-auto: validate
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    open-in-view: false
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/master.xml
    default-schema: timewars_db
    contexts: dev
  #    drop-first: true

  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com

server:
  port: 8080

application:
  client-base-url: http://localhost:4200
  cors:
    allowed-origins: http://localhost:4200
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"
    allow-credentials: false
    max-age: 300

secret:
  app:
    jwtSecret: "AQCa9l1Zs2yhPiSfjIU9PYqGoXkuvSnfJhHdpa4pwnfg3AtKzNI4PCWHRTp+rNYk5sqHJY300XlYcWD2WAO5ONDoPAQbR/i+WN5+nMljv407rxMtyn8Fa/0e9ICII/OS9vB7x1l4kE0OKKBEJiEkdcbDQS+JfdJqRBV5HiQFQrjLpG525VddRkCbcW046Z1XlWQOaOrdDNP3hC8BWW8d+0AYTFdpIFrAeYQxpRf3dJWbEK2aUjxZUbHbgXlUiFkFhtaq22FpjKK9Vkl+TLhl1K0wTc54wPQD1Szb1Ap8UZRR5Vi1OArOCIRWeJvAKw5ktZmgKbBjfI34ba5m7VbiSrVDHBZxExNmk5mFK8nNx+vznMPOwcAn6sMRuXin4SPSbsUpvDAzR0hxJcfWnodxRMGWeFu76ctfykTTcxtmU0j7bVqYKK0ewTArATnR68PtF+4lCnaYHLMl99AxWNfza806"
    jwtExpirationMs: 86400000